openapi: 3.0.2
info:
  version: 0.0.1
  title: gaussian process regression api
paths:
  /ml/predict:
    delete:
      tags:
        - ml
      summary: get prediction data
      description: get predicted next data and predicted data
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ml.getPredictionResponse'
components:
  schemas:
    ml.getPredictionResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            predicted_data:
              type: array
              items:
                type: object
                properties:
                  y_value:
                    type: number
                  x_value:
                    type: number
                  lower_bound:
                    type: number
                  upper_bound:
                    type: number
                required:
                  - y_value
                  - x_value
                  - lower_bound
                  - upper_bound
            predicted_next_data:
              type: object
              properties:
                y_value:
                  type: number
                x_value:
                  type: number
                lower_bound:
                  type: number
                upper_bound:
                  type: number
              required:
                - y_value
                - x_value
                - lower_bound
                - upper_bound
          required:
            - predicted_data
            - predicted_next_data
      required:
        - response
      example:
        response:
          predicted_data:
            - y_value: 0.1
              x_value: 0
              lower_bound: 0.1
              upper_bound: 0.1
            - y_value: 0.2
              x_value: 1
              lower_bound: 0.2
              upper_bound: 0.2
            - y_value: 0.3
              x_value: 2
              lower_bound: 0.3
              upper_bound: 0.3
            - y_value: 0.4
              x_value: 3
              lower_bound: 0.4
              upper_bound: 0.4
          predicted_next_data:
            y_value: 0.5
            x_value: 4
            lower_bound: 0.5
            upper_bound: 0.5
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
servers:
  - url: '{server}'
    variables:
      server:
        default: 'http://localhost:8000'

