openapi: 3.0.2
info:
  version: 0.0.1
  title: gaussian process regression api
paths:
  /ml/predict:
    delete:
      tags:
        - ml
      summary: get prediction data
      description: get predicted next data and predicted data
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ml.getPredictionResponse'
components:
  schemas:
    ml.getPredictionResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            predicted_data:
              type: array
              items:
                type: object
                properties:
                  value:
                    type: number
                  time:
                    type: string
                    format: date-time
                  lower_bound:
                    type: number
                  upper_bound:
                    type: number
                required:
                  - value
                  - time
                  - lower_bound
                  - upper_bound
            predicted_next_data:
              type: object
              properties:
                value:
                  type: number
                time:
                  type: string
                  format: date-time
                lower_bound:
                  type: number
                upper_bound:
                  type: number
              required:
                - value
                - time
                - lower_bound
                - upper_bound
          required:
            - predicted_data
            - predicted_next_data
      required:
        - response
      example:
        response:
          predicted_data:
            - value: 0.1
              time: '2020-01-01T00:00:01Z'
              lower_bound: 0.1
              upper_bound: 0.1
            - value: 0.2
              time: '2020-01-01T00:00:02Z'
              lower_bound: 0.2
              upper_bound: 0.2
            - value: 0.3
              time: '2020-01-01T00:00:03Z'
              lower_bound: 0.3
              upper_bound: 0.3
            - value: 0.4
              time: '2020-01-01T00:00:04Z'
              lower_bound: 0.4
              upper_bound: 0.4
          predicted_next_data:
            value: 0.5
            time: '2020-01-01T00:00:05Z'
            lower_bound: 0.5
            upper_bound: 0.5
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
servers:
  - url: '{server}'
    variables:
      server:
        default: 'http://localhost:8000'

